package cognition

import "errors"

var (
	ErrActionFailed                       = errors.New("cognition action failed")
	ErrAuthorityDenied                    = errors.New("cognition authority denied")
	ErrCoordinatorBudgetExhausted         = errors.New("cognition coordinator budget exhausted")
	ErrInvalidAction                      = errors.New("invalid cognition action")
	ErrInvalidActionCatalog               = errors.New("invalid cognition action catalog")
	ErrInvalidActionSchema                = errors.New("invalid cognition action schema")
	ErrInvalidAttempt                     = errors.New("invalid cognition attempt reference")
	ErrInvalidBeliefRevision              = errors.New("invalid cognition belief revision")
	ErrInvalidCompletionCheck             = errors.New("invalid cognition completion check")
	ErrInvalidCompletionAuthority         = errors.New("invalid cognition completion authority")
	ErrInvalidCompletionResult            = errors.New("invalid cognition completion result")
	ErrInvalidContextProjection           = errors.New("invalid cognition context projection reference")
	ErrInvalidDecision                    = errors.New("invalid cognition decision")
	ErrInvalidEvidence                    = errors.New("invalid cognition evidence")
	ErrInvalidEffect                      = errors.New("invalid cognition effect")
	ErrInvalidFailure                     = errors.New("invalid cognition action failure")
	ErrInvalidGoal                        = errors.New("invalid cognition goal")
	ErrInvalidIdentity                    = errors.New("invalid cognition identity")
	ErrInvalidObservation                 = errors.New("invalid cognition observation")
	ErrInvalidObligation                  = errors.New("invalid cognition obligation")
	ErrInvalidObligationIdentity          = errors.New("invalid cognition obligation identity")
	ErrInvalidObligationProposal          = errors.New("invalid cognition obligation proposal")
	ErrInvalidObligationMaterialization   = errors.New("invalid cognition obligation materialization")
	ErrInvalidObligationGeneration        = errors.New("invalid cognition obligation generation")
	ErrInvalidObligationGraph             = errors.New("invalid cognition obligation graph")
	ErrInvalidObligationTransition        = errors.New("invalid cognition obligation transition")
	ErrInvalidPlanRevision                = errors.New("invalid cognition plan revision")
	ErrInvalidPlanRevisionMaterialization = errors.New("invalid cognition plan revision materialization")
	ErrInvalidPredicate                   = errors.New("invalid cognition predicate")
	ErrInvalidRevision                    = errors.New("invalid cognition world revision")
	ErrInvalidRuntimeBudget               = errors.New("invalid cognition runtime budget")
	ErrInvalidRuntimeSnapshot             = errors.New("invalid cognition runtime snapshot")
	ErrInvalidScenario                    = errors.New("invalid cognition scenario reference")
	ErrInvalidTransition                  = errors.New("invalid cognition transition")
	ErrEnvironmentJournalConflict         = errors.New("cognition environment journal conflict")
	ErrEnvironmentJournalNotStarted       = errors.New("cognition environment journal is not started")
	ErrEnvironmentJournalStaleRevision    = errors.New("cognition environment journal revision is stale")
	ErrEnvironmentJournalTerminal         = errors.New("cognition environment journal is terminal")
	ErrPolicyFailed                       = errors.New("cognition policy failed")
	ErrPolicyUnavailable                  = errors.New("cognition policy unavailable")
	ErrUnsupportedCompletionPredicate     = errors.New("unsupported cognition completion predicate")
)
