package repository

import "testing"

func TestGeneratedGoSourceMarkerIsCanonicalAndLeading(t *testing.T) {
	t.Parallel()
	for _, source := range []string{
		"// Code generated by tool. DO NOT EDIT.\npackage generated\n",
		"// license\n\n// Code generated by tool. DO NOT EDIT.\npackage generated\n",
	} {
		if !GeneratedGoSource([]byte(source)) {
			t.Fatalf("canonical generated source was not detected: %q", source)
		}
	}
	for _, source := range []string{
		"package handwritten\n// Code generated by tool. DO NOT EDIT.\n",
		"// Code generated by tool\npackage handwritten\n",
	} {
		if GeneratedGoSource([]byte(source)) {
			t.Fatalf("handwritten source was classified as generated: %q", source)
		}
	}
}
