import { Controller } from "@hotwired/stimulus";

export abstract class ChatTargetsController extends Controller {
  static targets = [
    "messages", "timeline", "input", "send", "status", "transport", "networkUrl", "job", "liveBadge", "activityDot", "activityText", "activityProblems", "eventCount", "panel",
    "jobFilter", "jobsList", "jobDetails", "memoryCandidates", "memoryList", "memoryKind", "memoryKindFilter", "memoryTags", "memoryContent",
    "statusOutput", "researchStatusOutput", "hostBridgeStatusOutput",
    "metricsOutput", "progress", "progressState", "progressLoading", "spinner", "modal", "modalPanel", "channelSelect", "newChannelDataSourceSelect", "newChannelModeSelect", "newChannelRoleplayFields", "newChannelRoleplayWorldName", "newChannelRoleplayViewpointName", "transcriptLoading", "typingIndicator", "roleplayPanel", "roleplayLoading", "roleplayWorkspaceLoading", "roleplayWorldDialog", "roleplayCharacterDialog", "roleplaySetupDialog", "roleplayCharacterEditorDialog", "roleplayPersona", "roleplayPersonaCreator", "roleplayNewPersona", "roleplayDraftParts", "roleplayDraftPartPool", "roleplayDraftPart", "slashPalette", "slashOptions",
  ];

  declare readonly messagesTarget: HTMLElement;
  declare readonly timelineTarget: HTMLElement;
  declare readonly inputTarget: HTMLTextAreaElement;
  declare readonly sendTarget: HTMLButtonElement;
  declare readonly statusTarget: HTMLElement;
  declare readonly transportTarget: HTMLElement;
  declare readonly networkUrlTarget: HTMLAnchorElement;
  declare readonly jobTarget: HTMLElement;
  declare readonly liveBadgeTarget: HTMLButtonElement;
  declare readonly activityDotTarget: HTMLElement;
  declare readonly activityTextTarget: HTMLElement;
  declare readonly activityProblemsTarget: HTMLElement;
  declare readonly eventCountTarget: HTMLElement;
  declare readonly panelTargets: HTMLElement[];
  declare readonly jobFilterTarget: HTMLSelectElement;
  declare readonly jobsListTarget: HTMLElement;
  declare readonly jobDetailsTarget: HTMLElement;
  declare readonly memoryCandidatesTarget: HTMLElement;
  declare readonly memoryListTarget: HTMLElement;
  declare readonly memoryKindTarget: HTMLSelectElement;
  declare readonly memoryKindFilterTarget: HTMLSelectElement;
  declare readonly memoryTagsTarget: HTMLInputElement;
  declare readonly memoryContentTarget: HTMLTextAreaElement;
  declare readonly statusOutputTarget: HTMLElement;
  declare readonly researchStatusOutputTarget: HTMLElement;
  declare readonly hostBridgeStatusOutputTarget: HTMLElement;
  declare readonly metricsOutputTarget: HTMLElement;
  declare readonly progressTarget: HTMLElement;
  declare readonly progressStateTarget: HTMLElement;
  declare readonly progressLoadingTarget: HTMLElement;
  declare readonly spinnerTarget: HTMLElement;
  declare readonly modalTarget: HTMLElement;
  declare readonly modalPanelTarget: HTMLElement;
  declare readonly hasMemoryListTarget: boolean;
  declare readonly hasStatusOutputTarget: boolean;
  declare readonly hasResearchStatusOutputTarget: boolean;
  declare readonly hasHostBridgeStatusOutputTarget: boolean;
  declare readonly hasMetricsOutputTarget: boolean;
  declare readonly hasProgressStateTarget: boolean;
  declare readonly hasProgressLoadingTarget: boolean;
  declare readonly hasModalTarget: boolean;
  declare readonly hasSpinnerTarget: boolean;
  declare readonly hasNetworkUrlTarget: boolean;
  declare readonly hasChannelSelectTarget: boolean;
  declare readonly hasJobsListTarget: boolean;
  declare readonly hasJobDetailsTarget: boolean;
  declare readonly hasMessagesTarget: boolean;
  declare readonly hasInputTarget: boolean;
  declare readonly hasSendTarget: boolean;
  declare readonly hasStatusTarget: boolean;
  declare readonly hasLiveBadgeTarget: boolean;
  declare readonly hasTransportTarget: boolean;
  declare readonly hasJobTarget: boolean;
  declare readonly hasEventCountTarget: boolean;
  declare readonly channelSelectTarget: HTMLSelectElement;
  declare readonly newChannelDataSourceSelectTarget: HTMLSelectElement;
  declare readonly hasNewChannelDataSourceSelectTarget: boolean;
  declare readonly newChannelModeSelectTarget: HTMLSelectElement;
  declare readonly hasNewChannelModeSelectTarget: boolean;
  declare readonly newChannelRoleplayFieldsTarget: HTMLElement;
  declare readonly hasNewChannelRoleplayFieldsTarget: boolean;
  declare readonly newChannelRoleplayWorldNameTarget: HTMLInputElement;
  declare readonly hasNewChannelRoleplayWorldNameTarget: boolean;
  declare readonly newChannelRoleplayViewpointNameTarget: HTMLInputElement;
  declare readonly hasNewChannelRoleplayViewpointNameTarget: boolean;
  declare readonly transcriptLoadingTarget: HTMLElement;
  declare readonly hasTranscriptLoadingTarget: boolean;
  declare readonly typingIndicatorTarget: HTMLElement;
  declare readonly hasTypingIndicatorTarget: boolean;
  declare readonly roleplayPanelTarget: HTMLElement;
  declare readonly hasRoleplayPanelTarget: boolean;
  declare readonly roleplayLoadingTarget: HTMLElement;
  declare readonly hasRoleplayLoadingTarget: boolean;
  declare readonly roleplayWorkspaceLoadingTarget: HTMLElement;
  declare readonly hasRoleplayWorkspaceLoadingTarget: boolean;
  declare readonly roleplayWorldDialogTarget: HTMLDialogElement;
  declare readonly roleplayCharacterDialogTarget: HTMLDialogElement;
  declare readonly roleplaySetupDialogTarget: HTMLDialogElement;
  declare readonly roleplayCharacterEditorDialogTarget: HTMLDialogElement;
  declare readonly roleplayPersonaTarget: HTMLSelectElement;
  declare readonly hasRoleplayPersonaTarget: boolean;
  declare readonly roleplayPersonaCreatorTarget: HTMLElement;
  declare readonly hasRoleplayPersonaCreatorTarget: boolean;
  declare readonly roleplayNewPersonaTarget: HTMLInputElement;
  declare readonly hasRoleplayNewPersonaTarget: boolean;
  declare readonly roleplayDraftPartsTarget: HTMLOListElement;
  declare readonly hasRoleplayDraftPartsTarget: boolean;
  declare readonly roleplayDraftPartPoolTarget: HTMLElement;
  declare readonly hasRoleplayDraftPartPoolTarget: boolean;
  declare readonly roleplayDraftPartTargets: HTMLElement[];
  declare readonly slashPaletteTarget: HTMLElement;
  declare readonly slashOptionsTarget: HTMLElement;
}
