package modelconfig

import (
	"fmt"
	"os"

	"github.com/gryph/omnidex/internal/llmprovider/catalog"
)

var removedEnvironmentKeys = removedModelEnvironmentKeys()

func removedModelEnvironmentKeys() []string {
	keys := []string{
		"OMNI_FAST_MODEL",
		"OMNI_GLUE_MODEL",
		"OMNI_REASONING_MODEL",
		"OMNI_PLANNER_MODEL",
		"OMNI_ANALYZER_MODEL",
		"OMNI_RESPONDER_MODEL",
		"OMNI_TAGGER_MODEL",
		"OMNI_SEARCH_MODEL",
		"OMNI_MEMORY_MODEL",
		"OMNIDEX_SKILLS_ROOT",
		"OMNI_EXECUTOR_MODEL",
		"OMNI_MODEL",
		"OMNI_CONVERSATION_MODEL",
		"OMNI_CONVERSATION_CONTEXT_SELECTION_MODEL",
		"OMNI_MEMORY_CONTEXT_SELECTION_MODEL",
		"OMNI_ROLEPLAY_NARRATIVE_CONTINUITY_MODEL",
		"OMNI_ROLEPLAY_VOICE_REWRITE_MODEL",
		"OMNI_ROLEPLAY_CANON_EXTRACTION_MODEL",
		"OMNI_ROLEPLAY_ONGOING_ACTION_MODEL",
		"OMNI_OBJECTIVE_ADVISORY_MODEL",
		"AZURE_OPENAI_DEPLOYMENT",
		"OMNI_SHELL_SPECIALIST_MODEL",
		"OLLAMA_MODEL_SPECIALIST_PLANNER",
		"OLLAMA_MODEL_SPECIALIST_TOOLING",
		"OLLAMA_MODEL_SPECIALIST_FILESYSTEM_RESEARCH",
		"OLLAMA_MODEL_SPECIALIST_INTENT_TAGGING",
		"OLLAMA_MODEL_SPECIALIST_MEMORY_RETRIEVAL",
		"OLLAMA_MODEL_SPECIALIST_WEB_RESEARCH",
		"OLLAMA_MODEL_SPECIALIST_SUBTASK_EXECUTOR",
		"OLLAMA_MODEL_SPECIALIST_ANALYSIS",
		"OLLAMA_MODEL_SPECIALIST_RESPONSE",
		"OLLAMA_MODEL_SPECIALIST_REVIEW_VERIFICATION",
		"OLLAMA_MODEL_SPECIALIST_MEDIA_CONTROL",
		"OLLAMA_MODEL_SPECIALIST_BROWSER_INSPECTION",
		"OLLAMA_MODEL_SPECIALIST_SCREEN_VISION",
		"OLLAMA_MODEL_SPECIALIST_SHELL_EXECUTION",
		"OLLAMA_MODEL_SPECIALIST_AUDIO_NOTES",
		"OLLAMA_MODEL_SPECIALIST_CODING_SURFACE",
		"OLLAMA_MODEL_SPECIALIST_CODING_PRODUCT_IDENTITY",
		"OLLAMA_MODEL_SPECIALIST_CODING_REQUIREMENT_PARTITION",
		"OLLAMA_MODEL_SPECIALIST_CODING_ARTIFACT_HANDLING",
		"OLLAMA_MODEL_SPECIALIST_CODING_CAPABILITY_RELATION",
		"OLLAMA_MODEL_SPECIALIST_CODING_SKILL_SELECTION",
		"OLLAMA_MODEL_SPECIALIST_CODING_SKILL_PROCEDURE",
		"OMNI_CODING_SKILL_PROCEDURE_MODEL",
		"OMNI_CODING_PRODUCT_IDENTITY_MODEL",
		"OMNI_CODING_REQUIREMENT_PARTITION_MODEL",
		"OMNI_CODING_WORKLOAD_REVIEW_MODEL",
		"OLLAMA_MODEL_SPECIALIST_CODING_FRAGMENT",
		"OLLAMA_MODEL_SPECIALIST_CODING_FRAGMENT_CORRECTION",
		"OMNI_CODING_REQUIREMENT_ADVISER_MODEL",
		"OLLAMA_MODEL_SPECIALIST_CODING_REQUIREMENT_ADVISER",
		"OMNI_CODING_REQUIREMENT_SPLIT_MODEL",
		"OLLAMA_MODEL_SPECIALIST_CODING_REQUIREMENT_SPLIT",
	}
	for _, definition := range catalog.Definitions() {
		keys = append(keys, definition.EnvironmentKeys("MODEL")...)
		for _, suffix := range []string{
			"MODEL_FAST", "MODEL_GLUE", "MODEL_REASONING", "MODEL_TAGGER", "MODEL_PLANNER",
			"MODEL_ANALYZER", "MODEL_RESPONDER", "MODEL_SEARCH", "MODEL_MEMORY",
		} {
			keys = append(keys, definition.EnvironmentKeys(suffix)...)
		}
	}
	return keys
}

func RemovedEnvironmentKeys() []string {
	keys := make([]string, len(removedEnvironmentKeys))
	copy(keys, removedEnvironmentKeys)
	return keys
}

func ValidateEnvironmentValues(values map[string]string) error {
	for _, key := range removedEnvironmentKeys {
		if _, exists := values[key]; exists {
			return fmt.Errorf("model environment setting %s was removed and is unsupported; delete this setting", key)
		}
	}
	return nil
}

func ValidateCurrentEnvironment() error {
	values := make(map[string]string)
	for _, key := range removedEnvironmentKeys {
		if value, exists := os.LookupEnv(key); exists {
			values[key] = value
		}
	}
	return ValidateEnvironmentValues(values)
}
