package worker

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestArtifactCandidateAuthorityRejectsGeneratedSourceBeforeInference(t *testing.T) {
	t.Parallel()
	snapshot, analysis := ambiguousDeletionFixture(t)
	physical := filepath.Join(snapshot.Root, "legacy_adapter.go")
	if err := os.WriteFile(
		physical,
		[]byte("// Code generated by fixture. DO NOT EDIT.\npackage verification\n\nfunc LegacyAdapter() int { return 1 }\n"),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	desiredStateGit(t, snapshot.Root, "add", "legacy_adapter.go")
	desiredStateGit(t, snapshot.Root, "commit", "-m", "generated candidate")
	snapshot, analysis = desiredStateReindex(t, t.Context(), snapshot.Root)
	_, err := buildArtifactCandidateAuthorities(
		t.Context(),
		"Remove whichever of ARTIFACT_1 or ARTIFACT_2 is obsolete.",
		ambiguousDeletionDirectives(), ambiguousDeletionIdentities(), snapshot, analysis,
	)
	if err == nil || !strings.Contains(err.Error(), "generated") {
		t.Fatalf("generated candidate error=%v", err)
	}
}

func TestArtifactCandidateAuthorityRejectsStaleSourceBeforeInference(t *testing.T) {
	t.Parallel()
	snapshot, analysis := ambiguousDeletionFixture(t)
	if err := os.WriteFile(
		filepath.Join(snapshot.Root, "legacy_adapter.go"),
		[]byte("package verification\n\nfunc LegacyAdapter() int { return 7 }\n"),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	_, err := buildArtifactCandidateAuthorities(
		t.Context(),
		"Remove whichever of ARTIFACT_1 or ARTIFACT_2 is obsolete.",
		ambiguousDeletionDirectives(), ambiguousDeletionIdentities(), snapshot, analysis,
	)
	if err == nil || !strings.Contains(err.Error(), "stale") {
		t.Fatalf("stale candidate error=%v", err)
	}
}
