package worker

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// laravelComposerLockTemplate is generated by Composer 2.10.2 from the exact
// registered root requirements on the PHP 8.3.30 platform. It resolves the
// official Laravel framework v13.29.0 release commit 6e2c363716964d8238cee7097b258119a984f0cf.
//
//go:embed static/laravel_13_composer_lock.json
var laravelComposerLockTemplate []byte

func validateLaravelComposerLock(source []byte) error {
	var lock struct {
		ContentHash      string `json:"content-hash"`
		PluginAPIVersion string `json:"plugin-api-version"`
		Packages         []struct {
			Name    string `json:"name"`
			Version string `json:"version"`
			Source  struct {
				Reference string `json:"reference"`
			} `json:"source"`
		} `json:"packages"`
		PackagesDev []json.RawMessage `json:"packages-dev"`
	}
	if err := json.Unmarshal(source, &lock); err != nil {
		return fmt.Errorf("decode registered Laravel Composer lock: %w", err)
	}
	if lock.ContentHash != laravelComposerContentHash || lock.PluginAPIVersion != "2.9.0" ||
		len(lock.Packages) == 0 || len(lock.PackagesDev) != 0 {
		return fmt.Errorf("registered Laravel Composer lock has unexpected root authority")
	}
	seen := make(map[string]struct{}, len(lock.Packages))
	frameworkFound := false
	for _, pkg := range lock.Packages {
		if pkg.Name == "" || pkg.Version == "" {
			return fmt.Errorf("registered Laravel Composer lock contains an incomplete package")
		}
		if _, duplicate := seen[pkg.Name]; duplicate {
			return fmt.Errorf("registered Laravel Composer lock repeats package %s", pkg.Name)
		}
		seen[pkg.Name] = struct{}{}
		if pkg.Name == "laravel/framework" {
			frameworkFound = pkg.Version == "v"+laravelFrameworkVersion &&
				pkg.Source.Reference == "6e2c363716964d8238cee7097b258119a984f0cf"
		}
	}
	if !frameworkFound {
		return fmt.Errorf("registered Laravel Composer lock lost framework v%s", laravelFrameworkVersion)
	}
	return nil
}
