package worker

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/gryph/omnidex/internal/assemblyline"
)

const genericRustCommandLineAdapter = "rust_command_line_capabilities_v1"

var rustCommandLineModulePattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$`)
var rustCommandLinePackageSegmentPattern = regexp.MustCompile(`^[a-z0-9]+(?:_[a-z0-9]+)*$`)

func compileGenericRustCommandLineBlueprint(
	packageName string,
	specification assemblyline.ApplicationSpecification,
	workload assemblyline.FrozenApplicationWorkload,
	capabilities directCodingCapabilityGraph,
	profile directCodingProjectVersionProfile,
	target assemblyline.TargetTree,
	coverage assemblyline.ApplicationFileCoveragePlan,
) (assemblyline.SourceBlueprint, []directCodingFileTask, error) {
	contexts, err := directCodingApplicationTaskContexts(workload)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	crateName, err := rustCommandLineCrateName(packageName)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	documents, err := genericRustCommandLineDocuments(
		crateName, specification, contexts, capabilities, coverage,
	)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	staticFiles, err := genericRustCommandLineStaticFiles(profile, packageName, crateName)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	return assemblyline.SourceBlueprint{Documents: documents}, staticFiles, nil
}

func genericRustCommandLineStaticFiles(
	profile directCodingProjectVersionProfile,
	packageName string,
	crateName string,
) ([]directCodingFileTask, error) {
	if strings.TrimSpace(packageName) == "" || strings.TrimSpace(crateName) == "" {
		return nil, fmt.Errorf("Rust package and crate identities are required")
	}
	edition, err := directCodingVersionComponent(profile, "rust_edition")
	if err != nil {
		return nil, err
	}
	rustVersion, err := directCodingVersionComponent(profile, "rust_version")
	if err != nil {
		return nil, err
	}
	lockVersion, err := directCodingVersionComponent(profile, "cargo_lock")
	if err != nil {
		return nil, err
	}
	if parsed, parseErr := strconv.Atoi(lockVersion); parseErr != nil || parsed <= 0 {
		return nil, fmt.Errorf("Rust profile Cargo lock version %q is invalid", lockVersion)
	}
	manifest := fmt.Sprintf(`[package]
name = %q
version = "0.1.0"
edition = %q
rust-version = %q
publish = false

[lib]
name = %q
path = "src/lib.rs"
`, packageName, edition, rustVersion, crateName)
	lockfile := fmt.Sprintf(`# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = %s

[[package]]
name = %q
version = "0.1.0"
	`, lockVersion, packageName)
	return []directCodingFileTask{
		{Path: "Cargo.toml", Content: []byte(manifest), Mode: 0o644},
		{Path: "Cargo.lock", Content: []byte(lockfile), Mode: 0o644},
	}, nil
}

func rustCommandLineCrateName(packageName string) (string, error) {
	segment := strings.ReplaceAll(strings.TrimSpace(packageName), "-", "_")
	if !rustCommandLinePackageSegmentPattern.MatchString(segment) {
		return "", fmt.Errorf("Rust package name %q cannot form a crate identifier", packageName)
	}
	return "omnidex_" + segment, nil
}
