package worker

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/gryph/omnidex/internal/assemblyline"
	"github.com/pelletier/go-toml/v2"
)

const genericRustCommandLineAdapter = "rust_command_line_capabilities_v1"

var rustCommandLineModulePattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$`)
var rustCommandLinePackageSegmentPattern = regexp.MustCompile(`^[a-z0-9]+(?:_[a-z0-9]+)*$`)

func compileGenericRustCommandLineBlueprint(
	packageName string,
	specification assemblyline.ApplicationSpecification,
	workload assemblyline.FrozenApplicationWorkload,
	capabilities directCodingCapabilityGraph,
	target assemblyline.TargetTree,
	coverage assemblyline.ApplicationFileCoveragePlan,
) (assemblyline.SourceBlueprint, []directCodingFileTask, error) {
	if err := specification.Validate(); err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	if specification.Surface != assemblyline.ApplicationSurfaceCommandLine {
		return assemblyline.SourceBlueprint{}, nil, fmt.Errorf(
			"generic Rust command-line stack does not support surface %s", specification.Surface,
		)
	}
	profile, err := directCodingVersionProfileForTargetTree(target)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	if err := validateDirectCodingCapabilityGraph(specification.Requirements, capabilities); err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	contexts, err := directCodingApplicationTaskContexts(workload)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	crateName, err := rustCommandLineCrateName(packageName)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	documents, err := genericRustCommandLineDocuments(
		crateName, specification, contexts, capabilities, coverage,
	)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	staticFiles, err := genericRustCommandLineStaticFiles(profile, packageName, crateName)
	if err != nil {
		return assemblyline.SourceBlueprint{}, nil, err
	}
	return assemblyline.SourceBlueprint{Documents: documents}, staticFiles, nil
}

func genericRustCommandLineStaticFiles(
	profile directCodingProjectVersionProfile,
	packageName string,
	crateName string,
) ([]directCodingFileTask, error) {
	if strings.TrimSpace(packageName) == "" || strings.TrimSpace(crateName) == "" {
		return nil, fmt.Errorf("Rust package and crate identities are required")
	}
	edition, err := directCodingVersionComponent(profile, "rust_edition")
	if err != nil {
		return nil, err
	}
	rustVersion, err := directCodingVersionComponent(profile, "rust_version")
	if err != nil {
		return nil, err
	}
	lockVersion, err := directCodingVersionComponent(profile, "cargo_lock")
	if err != nil {
		return nil, err
	}
	if parsed, parseErr := strconv.Atoi(lockVersion); parseErr != nil || parsed <= 0 {
		return nil, fmt.Errorf("Rust profile Cargo lock version %q is invalid", lockVersion)
	}
	manifest := fmt.Sprintf(`[package]
name = %q
version = "0.1.0"
edition = %q
rust-version = %q
publish = false

[lib]
name = %q
path = "src/lib.rs"
`, packageName, edition, rustVersion, crateName)
	lockfile := fmt.Sprintf(`# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = %s

[[package]]
name = %q
version = "0.1.0"
`, lockVersion, packageName)
	return []directCodingFileTask{
		{Path: ".gitignore", Content: "target\n"},
		{Path: "Cargo.toml", Content: manifest},
		{Path: "Cargo.lock", Content: lockfile},
	}, nil
}

func rustCommandLineCrateName(packageName string) (string, error) {
	segment := strings.ReplaceAll(strings.TrimSpace(packageName), "-", "_")
	if !rustCommandLinePackageSegmentPattern.MatchString(segment) {
		return "", fmt.Errorf("Rust package name %q cannot form a crate identifier", packageName)
	}
	return "omnidex_" + segment, nil
}

func validateRustCommandLineAssembly(assembly directCodingAssembly) error {
	files := make(map[string]string, len(assembly.Files))
	for _, file := range assembly.Files {
		files[file.Path] = file.Content
	}
	for _, required := range []string{
		"Cargo.toml", "Cargo.lock", ".gitignore",
		"src/runtime.rs", "src/lib.rs", "src/main.rs",
	} {
		if _, exists := files[required]; !exists {
			return fmt.Errorf("Rust command-line assembly lacks code-owned artifact %s", required)
		}
	}
	var manifest struct {
		Package struct {
			Name        string `toml:"name"`
			Version     string `toml:"version"`
			Edition     string `toml:"edition"`
			RustVersion string `toml:"rust-version"`
		} `toml:"package"`
		Library struct {
			Name string `toml:"name"`
			Path string `toml:"path"`
		} `toml:"lib"`
	}
	if err := toml.Unmarshal([]byte(files["Cargo.toml"]), &manifest); err != nil {
		return fmt.Errorf("decode Rust command-line manifest: %w", err)
	}
	if manifest.Package.Name == "" || manifest.Package.Version != "0.1.0" ||
		manifest.Package.Edition == "" || manifest.Package.RustVersion == "" {
		return fmt.Errorf("Rust command-line manifest has invalid package authority")
	}
	if manifest.Library.Path != "src/lib.rs" ||
		!rustCommandLineModulePattern.MatchString(manifest.Library.Name) {
		return fmt.Errorf("Rust command-line manifest has invalid library authority")
	}
	var lockfile struct {
		Version  int `toml:"version"`
		Packages []struct {
			Name    string `toml:"name"`
			Version string `toml:"version"`
		} `toml:"package"`
	}
	if err := toml.Unmarshal([]byte(files["Cargo.lock"]), &lockfile); err != nil {
		return fmt.Errorf("decode Rust command-line lockfile: %w", err)
	}
	if lockfile.Version <= 0 || len(lockfile.Packages) != 1 ||
		lockfile.Packages[0].Name != manifest.Package.Name ||
		lockfile.Packages[0].Version != manifest.Package.Version {
		return fmt.Errorf("Rust command-line lockfile differs from its dependency-free manifest")
	}
	return nil
}
