package queue

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestPostgresWorkspaceMutationAPIAppliesVerifiesAndReplaysTerminal(t *testing.T) {
	fixture := newWorkspaceMutationDatabaseFixture(t, "verified")
	var calls workspaceMutationCallbackCounts
	result, err := fixture.repository.ExecuteWorkspaceMutation(
		fixture.ctx, fixture.authority, fixture.command,
		workspaceMutationFixtureCallbacks(fixture, true, &calls),
	)
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != workspaceMutationVerified || !result.VerificationSucceeded ||
		result.MutationEvidenceID <= 0 || len(result.CommandEvidenceIDs) != 1 ||
		result.CommandEvidenceIDs[0] <= result.MutationEvidenceID ||
		result.VerificationEvidenceID <= result.CommandEvidenceIDs[0] {
		t.Fatalf("verified workspace mutation result=%+v", result)
	}
	if calls != (workspaceMutationCallbackCounts{observe: 4, apply: 1, verify: 1}) {
		t.Fatalf("verified workspace mutation callback counts=%+v", calls)
	}
	content, err := os.ReadFile(filepath.Join(fixture.root, "generated", "value.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != "generated by workspace mutation\n" {
		t.Fatalf("generated file content=%q", content)
	}

	var replayCalls workspaceMutationCallbackCounts
	replayed, err := fixture.repository.ExecuteWorkspaceMutation(
		fixture.ctx, fixture.authority, fixture.command,
		workspaceMutationForbiddenReplayCallbacks(&replayCalls),
	)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(replayed, result) {
		t.Fatalf("terminal replay=%+v want %+v", replayed, result)
	}
	if replayCalls != (workspaceMutationCallbackCounts{}) {
		t.Fatalf("terminal replay ran callbacks=%+v", replayCalls)
	}
	assertWorkspaceMutationTerminalRow(t, fixture, result, "", 1, 1)
}

func TestPostgresWorkspaceMutationAPIPersistsAuthoritativeVerificationFailure(t *testing.T) {
	fixture := newWorkspaceMutationDatabaseFixture(t, "verification-failed")
	var calls workspaceMutationCallbackCounts
	result, err := fixture.repository.ExecuteWorkspaceMutation(
		fixture.ctx, fixture.authority, fixture.command,
		workspaceMutationFixtureCallbacks(fixture, false, &calls),
	)
	if err != nil {
		t.Fatal(err)
	}
	if result.Status != workspaceMutationVerificationFailed || result.VerificationSucceeded ||
		result.MutationEvidenceID <= 0 || len(result.CommandEvidenceIDs) != 1 ||
		result.VerificationEvidenceID <= 0 {
		t.Fatalf("failed workspace verification result=%+v", result)
	}
	if calls != (workspaceMutationCallbackCounts{observe: 4, apply: 1, verify: 1}) {
		t.Fatalf("failed workspace verification callback counts=%+v", calls)
	}

	var replayCalls workspaceMutationCallbackCounts
	replayed, err := fixture.repository.ExecuteWorkspaceMutation(
		fixture.ctx, fixture.authority, fixture.command,
		workspaceMutationForbiddenReplayCallbacks(&replayCalls),
	)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(replayed, result) {
		t.Fatalf("failed terminal replay=%+v want %+v", replayed, result)
	}
	if replayCalls != (workspaceMutationCallbackCounts{}) {
		t.Fatalf("failed terminal replay ran callbacks=%+v", replayCalls)
	}
	assertWorkspaceMutationTerminalRow(
		t, fixture, result, "generated file verification failed", 1, 1,
	)
}

func assertWorkspaceMutationTerminalRow(
	t *testing.T,
	fixture workspaceMutationDatabaseFixture,
	result WorkspaceMutationResult,
	wantError string,
	wantApplyAttempts, wantVerificationAttempts int,
) {
	t.Helper()
	var status, lastError string
	var applyAttempts, verificationAttempts, evidenceCount int
	if err := fixture.pool.QueryRow(fixture.ctx, `
		SELECT status,COALESCE(last_error,''),apply_attempt_count,verification_attempt_count
		FROM workspace_mutation_operations WHERE id=$1
	`, result.OperationID).Scan(
		&status, &lastError, &applyAttempts, &verificationAttempts,
	); err != nil {
		t.Fatal(err)
	}
	if status != result.Status || lastError != wantError ||
		applyAttempts != wantApplyAttempts || verificationAttempts != wantVerificationAttempts {
		t.Fatalf(
			"terminal workspace mutation row=%s/%q/%d/%d want %s/%q/%d/%d",
			status, lastError, applyAttempts, verificationAttempts,
			result.Status, wantError, wantApplyAttempts, wantVerificationAttempts,
		)
	}
	if err := fixture.pool.QueryRow(fixture.ctx, `
		SELECT COUNT(*) FROM evidence
		WHERE job_id=$1 AND source_type IN (
			'workspace','workspace_verification','workspace_mutation'
		)
	`, fixture.command.JobID).Scan(&evidenceCount); err != nil {
		t.Fatal(err)
	}
	if evidenceCount != 3 {
		t.Fatalf("terminal workspace mutation evidence count=%d want 3", evidenceCount)
	}
	unresolved, err := fixture.repository.UnresolvedWorkspaceMutation(
		fixture.ctx, fixture.command.JobID, fixture.command.Generation,
	)
	if err != nil {
		t.Fatal(err)
	}
	if unresolved != nil {
		t.Fatalf("terminal workspace mutation remained unresolved: %+v", unresolved)
	}
}
