package queue

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/gryph/omnidex/internal/evidence"
	"github.com/gryph/omnidex/internal/model"
	workspacefacts "github.com/gryph/omnidex/internal/workspace"
	"github.com/jackc/pgx/v5/pgxpool"
)

type workspaceMutationDatabaseFixture struct {
	repository          *Repository
	pool                *pgxpool.Pool
	ctx                 context.Context
	root                string
	authority           model.StepAttemptAuthority
	command             WorkspaceMutationCommand
	stage               *workspacefacts.StagedMutation
	verificationCommand string
}

func newWorkspaceMutationDatabaseFixture(
	t *testing.T,
	label string,
) workspaceMutationDatabaseFixture {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	t.Cleanup(cancel)
	pool := openIsolatedDatabasePool(t)
	repository := New(pool)
	if err := repository.ResetDatabase(ctx, loadCurrentDatabaseSetup(t)); err != nil {
		t.Fatal(err)
	}

	root := t.TempDir()
	source, err := workspacefacts.Capture(ctx, root)
	if err != nil {
		t.Fatal(err)
	}
	plan, err := workspacefacts.PlanMutation(
		ctx,
		source,
		"objective_"+queueTestSHA256("workspace-api-"+label),
		[]workspacefacts.DesiredFileState{{
			Path: "generated/value.txt", Present: true,
			Content: []byte("generated by workspace mutation\n"), Mode: 0o644,
		}},
	)
	if err != nil {
		t.Fatal(err)
	}
	stage, err := workspacefacts.StageMutation(ctx, source, plan)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := stage.Cleanup(); err != nil {
			t.Error(err)
		}
	})

	project, err := repository.CreateProject(ctx, "workspace-api-"+label, root, "")
	if err != nil {
		t.Fatal(err)
	}
	marker := fmt.Sprintf("workspace-api-%s-%d", label, time.Now().UnixNano())
	metadata := []byte(fmt.Sprintf(`{"project_id":%d,"client_cwd":%q}`, project.ID, root))
	job, err := repository.EnqueueJob(ctx, marker, model.PipelineCoding, metadata)
	if err != nil {
		t.Fatal(err)
	}
	claim, err := repository.ClaimNextStep(ctx, marker+"-worker")
	if err != nil {
		t.Fatal(err)
	}
	if claim == nil || claim.Job.ID != job.ID {
		t.Fatalf("workspace mutation claim=%+v want job %d", claim, job.ID)
	}

	verificationCommand := "verify generated/value.txt"
	verification, err := NewWorkspaceMutationVerificationPlan(
		[]WorkspaceMutationVerificationIntent{{
			Kind: evidence.KindTestResult, Command: verificationCommand,
		}},
	)
	if err != nil {
		t.Fatal(err)
	}
	command := WorkspaceMutationCommand{
		JobID: job.ID, StepID: claim.Step.ID, Generation: claim.Step.Generation,
		CreatorAttempt: claim.Authority.Attempt, CreatorWorkerID: claim.Authority.WorkerID,
		ProjectID: project.ID, ProjectLocation: root, Plan: plan, Verification: verification,
	}
	return workspaceMutationDatabaseFixture{
		repository: repository, pool: pool, ctx: ctx, root: root,
		authority: claim.Authority, command: command, stage: stage,
		verificationCommand: verificationCommand,
	}
}

type workspaceMutationCallbackCounts struct {
	observe int
	apply   int
	verify  int
}

func workspaceMutationFixtureCallbacks(
	fixture workspaceMutationDatabaseFixture,
	succeeded bool,
	counts *workspaceMutationCallbackCounts,
) WorkspaceMutationCallbacks {
	return WorkspaceMutationCallbacks{
		Observe: func(ctx context.Context, command WorkspaceMutationCommand) (WorkspaceMutationObservation, error) {
			counts.observe++
			observed, err := workspacefacts.Capture(ctx, command.Plan.WorkspaceRoot)
			if err != nil {
				return "", err
			}
			if observed.ID == command.Plan.SourceStateID {
				return WorkspaceMutationSource, nil
			}
			if err := command.Plan.VerifyExpected(observed); err == nil {
				return WorkspaceMutationPost, nil
			}
			return WorkspaceMutationIndeterminate, nil
		},
		Apply: func(ctx context.Context, command WorkspaceMutationCommand) error {
			counts.apply++
			if command.Plan.ID != fixture.stage.Plan().ID {
				return fmt.Errorf("workspace mutation callback received a foreign stage")
			}
			_, err := fixture.stage.ApplyVerified(ctx)
			return err
		},
		Verify: func(_ context.Context, command WorkspaceMutationCommand) (WorkspaceMutationVerificationResult, error) {
			counts.verify++
			failure := ""
			if !succeeded {
				failure = "generated file verification failed"
			}
			return WorkspaceMutationVerificationResult{
				Succeeded: succeeded, Failure: failure,
				CommandEvidence: []evidence.Record{{
					JobID: command.JobID, StepID: command.StepID,
					Kind: evidence.KindTestResult, Command: fixture.verificationCommand,
					Metadata: map[string]any{"succeeded": succeeded},
				}},
			}, nil
		},
	}
}

func workspaceMutationForbiddenReplayCallbacks(
	counts *workspaceMutationCallbackCounts,
) WorkspaceMutationCallbacks {
	callbackErr := fmt.Errorf("terminal workspace mutation replay callback ran")
	return WorkspaceMutationCallbacks{
		Observe: func(context.Context, WorkspaceMutationCommand) (WorkspaceMutationObservation, error) {
			counts.observe++
			return "", callbackErr
		},
		Apply: func(context.Context, WorkspaceMutationCommand) error {
			counts.apply++
			return callbackErr
		},
		Verify: func(context.Context, WorkspaceMutationCommand) (WorkspaceMutationVerificationResult, error) {
			counts.verify++
			return WorkspaceMutationVerificationResult{}, callbackErr
		},
	}
}
