
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/gryph/omnidex/internal/cognitionreplay"


)

var tests = []testing.InternalTest{

	{"TestAblationSemanticProjectionUsesDistinctFrozenRegistry", _test.TestAblationSemanticProjectionUsesDistinctFrozenRegistry},

	{"TestAblationAndProductionSemanticRegistriesAreIsolated", _test.TestAblationAndProductionSemanticRegistriesAreIsolated},

	{"TestAblationSemanticProjectionSeparatesPrivateContaminatedOverlay", _test.TestAblationSemanticProjectionSeparatesPrivateContaminatedOverlay},

	{"TestAblationSemanticProjectionAllowsContentDedupButRequiresJSONRoots", _test.TestAblationSemanticProjectionAllowsContentDedupButRequiresJSONRoots},

	{"TestStructuralBaseExportIsDeterministicAndVerifiable", _test.TestStructuralBaseExportIsDeterministicAndVerifiable},

	{"TestHandBuiltOpaqueStructuralReplayCannotBecomeSeriousEvidence", _test.TestHandBuiltOpaqueStructuralReplayCannotBecomeSeriousEvidence},

	{"TestBasePagesLargeOrderedStreamsAndBindsEverySourceKindMapping", _test.TestBasePagesLargeOrderedStreamsAndBindsEverySourceKindMapping},

	{"TestBaseVerifierRejectsMissingSourceKindMapping", _test.TestBaseVerifierRejectsMissingSourceKindMapping},

	{"TestEventTimingRequiresOneCitedTypedTimestampWithinEpisode", _test.TestEventTimingRequiresOneCitedTypedTimestampWithinEpisode},

	{"TestPublicEventRegistryKeepsLifecycleAndEpistemicTransitionsDistinct", _test.TestPublicEventRegistryKeepsLifecycleAndEpistemicTransitionsDistinct},

	{"TestBaseRejectsOrphanAndInexactAuthority", _test.TestBaseRejectsOrphanAndInexactAuthority},

	{"TestBaseVerifierRejectsAlteredMissingReorderedAndPrivateContainerData", _test.TestBaseVerifierRejectsAlteredMissingReorderedAndPrivateContainerData},

	{"TestChunkedBlobFileIsDeterministicAndRoleBound", _test.TestChunkedBlobFileIsDeterministicAndRoleBound},

	{"TestChunkedBlobRejectsMissingExtraDuplicateReorderedAndAlteredData", _test.TestChunkedBlobRejectsMissingExtraDuplicateReorderedAndAlteredData},

	{"TestChunkedBlobFileRejectsSymlink", _test.TestChunkedBlobFileRejectsSymlink},

	{"TestChunkedBlobFileRejectsMutationBeforeOpenHandleVerification", _test.TestChunkedBlobFileRejectsMutationBeforeOpenHandleVerification},

	{"TestChunkedBlobFileRejectsPathReplacementWhileHandleIsOpen", _test.TestChunkedBlobFileRejectsPathReplacementWhileHandleIsOpen},

	{"TestChunkedBlobManifestCannotCiteItsOwnManifestBlob", _test.TestChunkedBlobManifestCannotCiteItsOwnManifestBlob},

	{"TestPublicBaseBindsOnlyPublicChunkedBlobs", _test.TestPublicBaseBindsOnlyPublicChunkedBlobs},

	{"TestPrivateOverlayBindsOnlyPrivateChunkedBlobs", _test.TestPrivateOverlayBindsOnlyPrivateChunkedBlobs},

	{"TestContainerRejectsDuplicateChunkManifestBinding", _test.TestContainerRejectsDuplicateChunkManifestBinding},

	{"TestKnowledgeCheckpointCadenceBoundsEveryTerminalPosition", _test.TestKnowledgeCheckpointCadenceBoundsEveryTerminalPosition},

	{"TestKnowledgeCheckpointCadenceRejectsShiftedBoundaries", _test.TestKnowledgeCheckpointCadenceRejectsShiftedBoundaries},

	{"TestKnowledgeCheckpointColdReopenFromEveryIntermediateState", _test.TestKnowledgeCheckpointColdReopenFromEveryIntermediateState},

	{"TestKnowledgeCheckpointChainRejectsMissingDuplicateReorderedOrModifiedDelta", _test.TestKnowledgeCheckpointChainRejectsMissingDuplicateReorderedOrModifiedDelta},

	{"TestKnowledgeCheckpointHashBindsPreviousIntervalAndState", _test.TestKnowledgeCheckpointHashBindsPreviousIntervalAndState},

	{"TestPrivateOverlayIsSeparateDeterministicAndBaseBound", _test.TestPrivateOverlayIsSeparateDeterministicAndBaseBound},

	{"TestPrivateOverlayTerminalAuthorityMustBeASealedEpisode", _test.TestPrivateOverlayTerminalAuthorityMustBeASealedEpisode},

	{"TestPrivateOverlayRejectsOrphanTruthData", _test.TestPrivateOverlayRejectsOrphanTruthData},

	{"TestPrivateOverlayRejectsInexactPrivateAuthority", _test.TestPrivateOverlayRejectsInexactPrivateAuthority},

	{"TestPrivateOverlayVerifierRejectsAlteredMissingReorderedAndOrphanData", _test.TestPrivateOverlayVerifierRejectsAlteredMissingReorderedAndOrphanData},

	{"TestSemanticProjectionReassemblesLargeAuthorityWithoutFallback", _test.TestSemanticProjectionReassemblesLargeAuthorityWithoutFallback},

	{"TestProjectionContentUsesOneStrictStorageVariant", _test.TestProjectionContentUsesOneStrictStorageVariant},

	{"TestPrivateProjectionContentRejectsPublicPrivateRoleSwap", _test.TestPrivateProjectionContentRejectsPublicPrivateRoleSwap},

	{"TestGenericReplayCannotMintSeriousSemanticEvidence", _test.TestGenericReplayCannotMintSeriousSemanticEvidence},

	{"TestBaseV2BindsOneSealedEpisodeTerminalAuthority", _test.TestBaseV2BindsOneSealedEpisodeTerminalAuthority},

	{"TestBaseVerifierRejectsLegacySchemaWithoutFallback", _test.TestBaseVerifierRejectsLegacySchemaWithoutFallback},

	{"TestTerminalAuthorityRejectsUnknownOrCrossVariantFields", _test.TestTerminalAuthorityRejectsUnknownOrCrossVariantFields},

	{"TestPreEpisodeSourceValidationRejectsShortInputWithoutPanic", _test.TestPreEpisodeSourceValidationRejectsShortInputWithoutPanic},

	{"TestChunkPublicBytesUsesOneExactBoundedManifest", _test.TestChunkPublicBytesUsesOneExactBoundedManifest},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/gryph/omnidex"
	testdeps.ImportPath = "github.com/gryph/omnidex/internal/cognitionreplay"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

