// Command stdlib-index records exported names from the registered Go toolchain.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	if runtime.Version() != "go1.24.0" || runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		return fmt.Errorf("standard-library index requires Go 1.24.0 on linux/amd64")
	}
	command := exec.Command("go", "list", "-json", "std")
	command.Env = append(os.Environ(), "CGO_ENABLED=0", "GOTOOLCHAIN=local")
	raw, err := command.Output()
	if err != nil {
		return fmt.Errorf("enumerate standard library: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	var lines []string
	for {
		var pkg struct {
			Name, ImportPath, Dir string
			GoFiles               []string
			Standard              bool
		}
		if err := decoder.Decode(&pkg); err != nil {
			if err == io.EOF {
				break
			}
			return err
		}
		if !pkg.Standard || pkg.Name == "main" || strings.Contains("/"+pkg.ImportPath+"/", "/internal/") || strings.Contains("/"+pkg.ImportPath+"/", "/vendor/") {
			continue
		}
		names := map[string]bool{}
		for _, filename := range pkg.GoFiles {
			file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(pkg.Dir, filename), nil, 0)
			if err != nil {
				return err
			}
			for _, declaration := range file.Decls {
				switch value := declaration.(type) {
				case *ast.FuncDecl:
					if value.Recv == nil && value.Name.IsExported() {
						names[value.Name.Name] = true
					}
				case *ast.GenDecl:
					for _, spec := range value.Specs {
						switch item := spec.(type) {
						case *ast.TypeSpec:
							if item.Name.IsExported() {
								names[item.Name.Name] = true
							}
						case *ast.ValueSpec:
							for _, name := range item.Names {
								if name.IsExported() {
									names[name.Name] = true
								}
							}
						}
					}
				}
			}
		}
		if len(names) == 0 {
			continue
		}
		var exported []string
		for name := range names {
			exported = append(exported, name)
		}
		sort.Strings(exported)
		lines = append(lines, pkg.Name+" "+pkg.ImportPath+" "+strings.Join(exported, " "))
	}
	sort.Strings(lines)
	fmt.Println("# Generated by cmd/stdlib-index with Go 1.24.0 linux/amd64, CGO_ENABLED=0.")
	fmt.Println(strings.Join(lines, "\n"))
	return nil
}
